platform: linux

image_resource:
  type: docker-image

inputs:
  - name: bin_gpdb
  - name: gpdb_src
  - name: plcontainer_src
  - name: plcontainer_client

outputs:
  - name: plcontainer_gpdb_build

params:
  DEV_RELEASE: devel
  OUTPUT: plcontainer_gpdb_build

run:
  path: plcontainer_src/concourse/scripts/build_plcontainer_prepare.sh
